name: boxfusion
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anywidget=0.9.21=pyhd8ed1ab_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h7ca4310_7
  - aws-c-cal=0.9.10=h346e085_1
  - aws-c-common=0.12.5=hb03c661_1
  - aws-c-compression=0.3.1=h7e655bb_8
  - aws-c-event-stream=0.5.6=h3cb25bf_6
  - aws-c-http=0.10.7=hc5c8343_4
  - aws-c-io=0.23.3=ha76f1cc_3
  - aws-c-mqtt=0.13.3=h3a25ec9_10
  - aws-c-s3=0.10.1=hcb69869_2
  - aws-c-sdkutils=0.2.4=h7e655bb_3
  - aws-checksums=0.2.7=h7e655bb_4
  - aws-crt-cpp=0.35.2=h2ceb62e_4
  - aws-sdk-cpp=1.11.606=hd6e39bc_7
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.15.0=h2a74896_1
  - azure-storage-common-cpp=12.11.0=h3d7a050_1
  - azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - ipython=8.37.0=pyh8f84b5b_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter-ui-poll=1.0.0=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=22.0.0=h2937f24_4_cuda
  - libarrow-acero=22.0.0=hb826db4_4_cuda
  - libarrow-compute=22.0.0=h58682fd_4_cuda
  - libarrow-dataset=22.0.0=hb826db4_4_cuda
  - libarrow-substrait=22.0.0=h9d9f3f8_4_cuda
  - libblas=3.11.0=4_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=4_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_15
  - libgcc-ng=15.2.0=h69a702a_15
  - libgfortran=15.2.0=h69a702a_15
  - libgfortran5=15.2.0=h68bc16d_15
  - libgomp=15.2.0=he0feb66_15
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=4_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=22.0.0=h31208bf_4_cuda
  - libpng=1.6.51=h421ea60_0
  - libprotobuf=6.31.1=h49aed37_2
  - libre2-11=2025.11.05=h7b12aa8_0
  - libsqlite=3.51.1=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_15
  - libstdcxx-ng=15.2.0=hdf11a46_15
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h9d88235_1
  - libutf8proc=2.11.2=hfe17d71_0
  - libuuid=2.41.2=h5347b49_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=h031cc0b_0
  - libxml2-16=2.15.1=hf2a90c1_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nlohmann_json=3.12.0=h54a6638_1
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - orc=2.2.1=hd747db4_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyh8b19718_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psygnal=0.15.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow-core=22.0.0=py310h0d81dc7_0_cuda
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.19=h3c07f61_2_cpython
  - python_abi=3.10=8_cp310
  - re2=2025.11.05=h5301d42_0
  - readline=8.2=h8c095d6_2
  - rerun-sdk=0.27.2=py310h7f0bd4e_0
  - s2n=1.6.0=h8399546_1
  - setuptools=80.9.0=pyhff2d567_0
  - snappy=1.2.2=h03e3b7b_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_ha0e22de_103
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - wrapt=2.0.1=py310h7c4b9e2_1
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.2=h54a6638_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - addict==2.4.0
      - annotated-types==0.7.0
      - anyio==4.12.0
      - beautifulsoup4==4.14.3
      - blinker==1.9.0
      - certifi==2025.11.12
      - click==8.3.1
      - clip==0.2.0
      - configargparse==1.7.1
      - cycler==0.12.1
      - dash==3.3.0
      - distro==1.9.0
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - flask==3.1.2
      - fonttools==4.61.0
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - google==3.0.0
      - google-auth==2.47.0
      - google-genai==1.60.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.7
      - idna==3.11
      - importlib-metadata==8.7.0
      - itsdangerous==2.2.0
      - kiwisolver==1.4.9
      - mako==1.3.10
      - markupsafe==2.1.5
      - narwhals==2.13.0
      - nbformat==5.10.4
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - open-clip-torch==3.2.0
      - open3d==0.19.0
      - opencv-python==4.12.0.88
      - pillow==11.3.0
      - plotly==6.5.0
      - pyarrow==22.0.0
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycuda==2025.1.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pytools==2025.2.5
      - pytope==0.0.4
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - rerun-notebook==0.27.2
      - retrying==1.4.2
      - rsa==4.9.1
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - shellingham==1.5.4
      - siphash24==1.8
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8.3
      - sympy==1.13.1
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - timm==1.0.22
      - torch==2.6.0+cu118
      - torchaudio==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - tqdm==4.67.1
      - triton==3.2.0
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - websockets==15.0.1
      - werkzeug==3.1.4
      - zipp==3.23.0
